
title: Conversas com os meus sobrinhos
email: tvieiragoncalves@gmail.com
description: >- Conversas sobre tudo e sobre nada, sobre coisas pequenas e coisas grandes, sobre coisas escondidas e conhecidas.:
Estas conversas contam com a distinta participação da Marizé e do Rafa, sendo moderadas pelo muito paciente Tiago Gonçalves.:

baseurl: "/pod-sobrinhos" # the subpath of your site, e.g. /blog
url: "https://tvieiragoncalves.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tiago_1989
github_username:  tvieiragoncavles


markdown: kramdown
remote_theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
